lanche = ['Hamburguer', 'Suco', 'Pizza', 'Pudim']
print('='*50)
lanche.append("Cookie") 
print('Essa função irá adicionar o elemento passado como argumento ao final da lista')
print(lanche)
print('='*50)
print('Laço de repetição com interação do usuário:')
val = list()
for cont in range(0, 4):
	val.append(str(input('Informe os nomes da lista: ')))
print(val)
print('='*50)
for c in enumerate(lanche):
	print(c)
print('='*50)
lanche.insert(0, 'Hot Dog')
print('Comando Insert adiciona um item na posição que eu quero')
print(lanche)
print('='*50)
print('Função Enumerate mostra a posição da lista')
for c in enumerate(lanche): 
	print(c)
print('='*50)
del lanche[4] 
print('Deletando item de uma Lista')
print(lanche)
print('='*50)
lanche.insert(4, 'Pudim')
print(lanche)
print('='*50)
lanche.pop(4) 
print('Deletando item de uma Lista. Normalmente ele elimina o ultimo elemento.')
print('mas posso passar parâmetro para eliminar o item que desejo.')
print(lanche)
print('='*50)
lanche.remove('Cookie') 
print('Eu removo o item pelo nome.')
print(lanche)
print('='*50)
print('Condição para remoção de item de lista.')
print('caso não saiba se tem o item na lista para não dar erro o programa')
if 'Hot Dog' in lanche: 
	lanche.remove('Hot Dog')
else:
	print('Não tem esse item na lista.')
print('='*50)
print('Criando lista atribuindo a uma variável e gerando números com função Range')
valores = list(range(4, 11))
print(valores)
print('='*50)
print('Criando valores aleatórios')
from random import randint
valor = [randint(1, 11), randint(1, 11), randint(1, 11), randint(1, 11), randint(1, 11)]
print(valor)
print('='*50)
print('Deixando os valores em ordem: ')
valor.sort()
print(valor)
print('='*50) 
print('Invertendo a ordem.')
valor.sort(reverse=True)
print(valor)
print('='*50)
print('Saber quantos elementos tem dentro da lista.')
print(len(valor))
print('='*50)



