algo = str(input("Digite algo: "))
print("O tipo primitivo desse valor é: ", type(algo))
print("Só tem espações: ", algo.isspace())
print("É um número: ", algo.isnumeric())
print("É alfabético: ", algo.isalpha())
print("É alfaNumérico: ", algo.isalnum())
print("Está em letras Maiúsculas: ", algo.isupper())
print("Está em letras Minúsculas: ", algo.islower())
print("Está capitalizada: ", algo.istitle())
