n = int(input("Informe um número: "))
print("O dobro desse número é: {}".format(n*2))
print("O triplo desse número é: {}".format(n*3))
print("A raiz quadrada desse número é: {}".format(n**(1/2)))
print("Esse número elevado ao quadrado é: {}".format(n**2))
print("Esse número elevado ao cubo é: {}".format(n**3))